### PR TITLE
Loaded in and plotted J10_s10_io raw emg data spectra

### PR DESCRIPTION
**Pull request by payton3801**
Plotted frequency spectra of the raw data using the same methods as we used for both the sinewave and noise spectra previously

### CODE REVIEW

**Comment by lwimala** [comment]
Can you drop the image of the spectra in this pull request?

**Comment by payton3801** [comment]
Screenshot 2024-09-26 224319
These are the same plots with different x-axes

**Comment by lwimala** [comment]
Can you plot this on log log instead of semilogy

**Comment by payton3801** [comment]
Screenshot 2024-09-26 231056
Is this right?

**Comment by lwimala** [comment]
Yeah it’s been a while since I looked at this data but that should be what we are looking for. I think those weird oscillation things at the higher frequencies is related to the hardware filtering they applied during acquisition. Could we start a fresh script for this analysis? It will just be less cluttered for review/etc.

**Comment by lwimala** [comment]
It would also be good to just plot the raw data over time. Can even be a short snippet (e.g., 30 seconds)

**Comment by payton3801** [comment]
Rectified EMG plot: time and frequency
image
image

**Review by payton3801 — COMMENTED** [review]
Overlaid* :(

**Comment by payton3801** [comment]
Plots for step 2: 
image

**Comment by payton3801** [comment]
Overlaid plots for Muscle GA / channel 2:
image

**Comment by payton3801** [comment]
Step 4: image

**Pull request merged**
